### ISSUE TITLE
npm giving me wrong version

### ISSUE THREAD

**Issue by jihopark** [realtime-framework/RealtimeMessaging-ReactNativeAndroidExample#2]
Hi, 

I succeeded in building the app with your library by the new instruction, but it seems that npm install is still giving your 1.0.1. I just downloaded directly from github instead, because it won't download 1.0.2.

Btw, your new instruction is so much clearer than 1.0.1. Now I am going to try to implement push messages, so I'll get back to you if there is any problem.

Keep up the good work!

**Comment by JoaoCaixinha** [comment]
Hi,
try to install again from npm, it should be available now.
Best reagards
