### ISSUE TITLE
Not receiving push notifications

### ISSUE THREAD

**Issue by jihopark** [realtime-framework/RealtimeMessaging-ReactNativeAndroidExample#3]
Hi, I'm testing with push notifications in ReactNative.

However, after following the steps in http://messaging-public.realtime.co/documentation/starting-guide/mobilePushGCM.html
- I configured the GCM API key in Realtime framework console.
- Changed the `MainActivity` to extend `RealtimePushNotificationActivity`
- Configured the `AndroidManifest.xml` (I realized the examples in your website is different from github readme)
- Running the example code from this repository

I get the messages in a certain channel when the app is on (it shows on the log u guys made), but when the app is not on foreground, it does not receive any push notification. (I'm testing on Genymotion which has Google Play Service installed. All the other apps receive push notification well)

Isn't it supposed to give me push notification if the msg is sent to the channel?

This is my AndroidManifest codes. I suspect there is something wrong here.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.plainx">

    <uses-permission android:name="android.permission.INTERNET" />

    <!-- For PUSH MESSAGES -->
    <permission android:name="com.plainx.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.plainx.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <application
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <!-- For PUSH MESSAGES -->
      <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
      <receiver
          android:name="co.realtime.reactnativemessagingandroid.GcmReceiver"
          android:permission="com.google.android.c2dm.permission.SEND" >
          <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <category android:name="com.plainx" />
          </intent-filter>
      </receiver>
    </application>

</manifest>
```

**Comment by jihopark** [comment]
changed the receiver code, but still not working..

**Comment by jihopark** [comment]
```
curl -i -X 'https://ortc-mobilepush.realtime.co/mp/publish' --data-binary '{"applicationKey": "***",
            "privateKey": "***",
            "channel" : "my_channel",
            "message" : "We have new articles for you",
            "payload" : "{
                \"sound\":\"default\",
                \"badge\" : \"2\",
                \"custom-property\" : \"value\",
                \"another-property\" : \"other-value\" }"
             }'
```

After doing this, the GCMReceiver onReceive is not initiated

**Comment by JoaoCaixinha** [comment]
Hi, did you configure the google project id in the application and the api key in the realtime subscriptions?

**Comment by jihopark** [comment]
yes i did that.

**Comment by jihopark** [comment]
@JoaoCaixinha 
Can u take a look at my code at https://github.com/jihopark/plainX-react-native/blob/rt-android-push/index.android.js

I did put my google project id on `index.android.js` and api key in your console.

```
curl -i -X POST 'https://ortc-mobilepush.realtime.co/mp/publish' --data-binary '{"applicationKey": "xxx",
            "privateKey": "xxx",
            "channel" : "my_channel",
            "message" : "We have new articles for you",
            "payload" : "{
                \"sound\":\"default\",
                \"badge\" : \"2\",
                \"custom-property\" : \"value\",
                \"another-property\" : \"other-value\" }"
             }'
```

Gives me 

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 0
Server: Jetty(7.0.2.v20100331)
```

But no messages arrive to the app when it is open, and no push notification arrives when it is closed.

Messages sent from our backend server using your Go Library are received  when the app is open, but not push messages.

**Comment by jihopark** [comment]
So I was thinking about why the push notificaiton isn't working. Below are the possibilities I have been exploring.
- [x] Genymotion Simulator isn't receiving push notification => not true, because i am receiving push notification after installing Google Play Service on other apps like Gmail, Yo, etc.
- [x] React Native Example Client code has a problem => not true, when I installed your Native Android Example App, it still didn't get the notification from the channel it was subscribed to when in background. It only shows the messages when the app is on foreground.
- [ ] GCM configuration on Google Developer Console is wrong - doubtful.. i just copied and paste the API key in your `edit subscription details`.
- [ ] There is something wrong with RealTime System - I cannot know. But I just tried to regenerate my GCM api key and update it on your console, it gave me an error (`There was an error while trying to process your request. Please try again later`) Can you investigate on this issue? @JoaoCaixinha 

My account is `long@mindworker.de`

I am one of the startup members, so we are trying to test whether we can use React Native Android & iOS for our first product. Since push notifications are one of our crucial features, we were testing how we can build this as easy as possible. Then we discovered your platform. We really love what you are building and plan to use it for production as long as it works!

So please help me solve this issue. Thanks!!

**Comment by JoaoCaixinha** [comment]
Hi jihopark, we verify your account subscription and find out that you do not have a google API key configurated. 
I send you also a working project with your code, you should not include the private key in your code.
If you find any more problem let us know.

**Comment by JoaoCaixinha** [comment]
Hi jihopark, did you manage to get push notifications to work? i see you didn't download the example project i send you on WeTransfer.

**Comment by jihopark** [comment]
hey @JoaoCaixinha i moved onto parse to use the notification.. i did configure the google api key. i think there is something wrong with your configuration page. thanks for the help though.
